version: "3.8"

services:

  prediction-service:
    container_name: "hayat_prediction_service"
    image: hayat_prediction_service:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
